# fly.toml app configuration file generated for skin-secrets on 2025-07-21T18:20:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skin-secrets'
primary_region = 'iad'

[experimental]
  enable_consul = true

[build]
  dockerfile = 'Dockerfile.production'

[deploy]
  release_command = 'sh -c "bin/rails db:migrate && bin/rails db:migrate SCOPE=queue && bin/rails db:migrate SCOPE=cache && bin/rails db:migrate SCOPE=cable"'

[env]
  AWS_REGION = 'us-east-1'
  PORT = '8080'
  RAILS_ENV = 'production'
  RAILS_LOG_TO_STDOUT = 'true'
  RAILS_MAX_THREADS = '5'
  RAILS_SERVE_STATIC_FILES = 'true'
  WEB_CONCURRENCY = '2'
  SOLID_QUEUE_IN_PUMA = 'true'

[mounts]
  source = "skin_secrets_data"
  destination = "/data"

[processes]
  app = 'bin/rails server'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/up'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

  [[vm.checks]]
    type = 'http'
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/up'
[[metrics]]
  port = 9091
  path = '/metrics' 
